AI ML Assignment-01

# Name:Rohan Rai
Campus:VIT VELLORE
Reg.No. 21BCE0440
Email_id:rohan.rai2021@vitstudent.ac.in

Task - 1 Create a pandas dataframe (DataFrame name as 'df') (10 observation and 5 features)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame([[1,2,3,4,5,],[5,8,9,6,5],[4,8,9,6,5],[4,8,7,8,4],[7,2,1,5,4],[4,5,6,8,7],[4,8,7,6,4],[7,4,9,1,2],[8,7,9,7,4],[6,5,4,8,5]])
df

   0  1  2  3  4
0  1  2  3  4  5
1  5  8  9  6  5
2  4  8  9  6  5
3  4  8  7  8  4
4  7  2  1  5  4
5  4  5  6  8  7
6  4  8  7  6  4
7  7  4  9  1  2
8  8  7  9  7  4
9  6  5  4  8  5

Task- 2 Check the info of 'df'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     int64
 1   1       10 non-null     int64
 2   2       10 non-null     int64
 3   3       10 non-null     int64
 4   4       10 non-null     int64
dtypes: int64(5)
memory usage: 528.0 bytes

Task 3- Check the descriptive statistics of 'df'

In [ ]:
df.describe()

               0          1          2         3          4
count  10.000000  10.000000  10.000000  10.00000  10.000000
mean    5.000000   5.700000   6.400000   5.90000   4.500000
std     2.054805   2.451757   2.875181   2.18327   1.269296
min     1.000000   2.000000   1.000000   1.00000   2.000000
25%     4.000000   4.250000   4.500000   5.25000   4.000000
50%     4.500000   6.000000   7.000000   6.00000   4.500000
75%     6.750000   8.000000   9.000000   7.75000   5.000000
max     8.000000   8.000000   9.000000   8.00000   7.000000

Task 4- check the 4th index observation with 'loc' slicing operator.

In [ ]:
df.loc[4]

0    7
1    2
2    1
3    5
4    4
Name: 4, dtype: int64

Task 5 - Check the null values in your 'df'

In [ ]:
df.isnull().any()

0    False
1    False
2    False
3    False
4    False
dtype: bool